[project]
name = "bq-multi-agent-app"
version = "0.1.0"
description = "BigQuery Multi-Agent Application with MCP and ADK"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=1.13.0",
]

[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "bq_multi_agent_app"
module-root = ""
